import type { Request, Response } from "express";
import multer from "multer";
import { getAI, getErrorMessage } from "../src/server/gemini";

const upload = multer({ storage: multer.memoryStorage() });

export const config = {
  api: {
    bodyParser: false,
  },
};

function runUpload(req: Request, res: Response): Promise<void> {
  return new Promise((resolve, reject) => {
    upload.single("photo")(req, res, (error) => {
      if (error) reject(error);
      else resolve();
    });
  });
}

export default async function handler(req: Request, res: Response) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    await runUpload(req, res);

    if (!req.file) {
      return res.status(400).json({ error: "No photo uploaded" });
    }

    const prompt = req.body?.prompt;
    if (!prompt) {
      return res.status(400).json({ error: "No prompt provided" });
    }

    const genAI = getAI(req);
    const response = await genAI.models.generateContent({
      model: "gemini-3.1-flash-image-preview",
      contents: {
        parts: [
          {
            inlineData: {
              data: req.file.buffer.toString("base64"),
              mimeType: req.file.mimetype,
            },
          },
          {
            text: `Take this photograph and edit the person's hair to match this specific style: "${prompt}". You MUST retain the exact same human face, identity, expression, pose, skin tone, features, and background. Only seamlessly change the hairstyle to look extremely natural, clean, photorealistic, and well-blended with the photo. Do not add any text, logos, or extra artifacts.`,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
          imageSize: "512px",
        },
      },
    });

    let base64Image: string | undefined;
    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData?.data) {
        base64Image = part.inlineData.data;
        break;
      }
    }

    if (!base64Image) {
      throw new Error("No image was successfully generated by the nano banana 2 model.");
    }

    res.json({ imageUrl: `data:image/png;base64,${base64Image}` });
  } catch (error) {
    console.error("Error generating hairstyle image via nano banana 2:", error);
    res.status(500).json({ error: getErrorMessage(error) });
  }
}
